#!/bin/bash
#
# show container list in a specific format

set -euo pipefail

#

if [ "$1" == "ports" ]; then
  sudo docker container ls --format "table {{.Image}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"
elif [ "$1" == "net" ]; then
  sudo docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }}{{range $k,$v := .NetworkSettings.Networks}} {{$k}}:{{.IPAddress}}{{end}}' | column -t
else
  echo "Usage: $0 [ports|net]"
  echo ""
  sudo docker container ls --format "table {{.Image}}\t{{.Names}}\t{{.Status}}"
fi
